schema_version: https://raw.githubusercontent.com/hubverse-org/hubPredEvalsData/main/inst/schema/v1.1.0/config_schema.json
rounds_idx: 0
transform_defaults:
  fun: log_shift
  args:
    offset: 1
  label: log
targets:
- target_id: SARI
  transform:
    fun: log_shift
    label: log
    args:
      offset: 1
    append: true
  metrics:
  - wis
  - ae_median
  - interval_coverage_50
  - interval_coverage_95
  relative_metrics:
  - wis
  - ae_median
  baseline: Regular Baseline
  disaggregate_by:
  - age_group
  - reference_date
  - horizon
  - target_end_date
eval_sets:
- eval_set_name: 2026 season, Overall age group
  task_filters:
    age_group:
    - "Overall"
    horizon:
    - -4
    - -3
    - -2
    - -1
    - 0
    - 1
    - 2
    - 3
    reference_date:
    - "2026-10-22"
    - "2026-11-19"
    - "2026-12-17"
    - "2026-01-14"
